name = "kotrac-site"
type = "javascript"

[build]
command = "pnpm install && pnpm run build:static"
cwd = "./"
watch_paths = ["client/src/**/*.{ts,tsx,css}"]

[build.upload]
dir = "dist/public"

[env.production]
name = "kotrac-site-prod"
